const professionMap: { [key: string]: string } = {
    Vanguard: "op_misc/profession_large_hub/icon_profession_pioneer_large.png",
    Defender: "op_misc/profession_large_hub/icon_profession_tank_large.png",
    Specialist:
        "op_misc/profession_large_hub/icon_profession_special_large.png",
    Caster: "op_misc/profession_large_hub/icon_profession_caster_large.png",
    Medic: "op_misc/profession_large_hub/icon_profession_medic_large.png",
    Supporter: "op_misc/profession_large_hub/icon_profession_support_large.png",
    WARRIOR: "op_misc/profession_large_hub/icon_profession_warrior_large.png",
    Sniper: "op_misc/profession_large_hub/icon_profession_sniper_large.png",
};

const subProfessionIdMap: { [key: string]: string } = {
    Abjurer: "op_misc/subprofessionicon/sub_blessing_icon.png",
    Agent: "op_misc/subprofessionicon/sub_agent_icon.png",
    Alchemist: "op_misc/subprofessionicon/sub_alchemist_icon.png",
    Ambusher: "op_misc/subprofessionicon/sub_stalker_icon.png",
    Artificer: "op_misc/subprofessionicon/sub_craftsman_icon.png",
    Artilleryman: "op_misc/subprofessionicon/sub_aoesniper_icon.png",
    "Arts Fighter": "op_misc/subprofessionicon/sub_artsfghter_icon.png",
    "Arts Protector": "op_misc/subprofessionicon/sub_artsprotector_icon.png",
    Bard: "op_misc/subprofessionicon/sub_bard_icon.png",
    Besieger: "op_misc/subprofessionicon/sub_siegesniper_icon.png",
    "Blast Caster": "op_misc/subprofessionicon/sub_blastcaster_icon.png",
    Centurion: "op_misc/subprofessionicon/sub_centurion_icon.png",
    "Chain Caster": "op_misc/subprofessionicon/sub_chain_icon.png",
    "Chain Medic": "op_misc/subprofessionicon/sub_chainhealer_icon.png",
    Charger: "op_misc/subprofessionicon/sub_charger_icon.png",
    "Core Caster": "op_misc/subprofessionicon/sub_corecaster_icon.png",
    Crusher: "op_misc/subprofessionicon/sub_crusher_icon.png",
    Deadeye: "op_misc/subprofessionicon/sub_longrange_icon.png",
    "Decel Binder": "op_misc/subprofessionicon/sub_slower_icon.png",
    Dollkeeper: "op_misc/subprofessionicon/sub_dollkeeper_icon.png",
    Dreadnought: "op_misc/subprofessionicon/sub_fearless_icon.png",
    Duelist: "op_misc/subprofessionicon/sub_duelist_icon.png",
    Earthshaker: "op_misc/subprofessionicon/sub_hammer_icon.png",
    Executor: "op_misc/subprofessionicon/sub_executor_icon.png",
    Fighter: "op_misc/subprofessionicon/sub_fighter_icon.png",
    Flinger: "op_misc/subprofessionicon/sub_bombarder_icon.png",
    Fortress: "op_misc/subprofessionicon/sub_fortress_icon.png",
    Geek: "op_misc/subprofessionicon/sub_geek_icon.png",
    Guardian: "op_misc/subprofessionicon/sub_guardian_icon.png",
    Heavyshooter: "op_misc/subprofessionicon/sub_closerange_icon.png",
    Hexer: "op_misc/subprofessionicon/sub_underminer_icon.png",
    Hookmaster: "op_misc/subprofessionicon/sub_hookmaster_icon.png",
    Hunter: "op_misc/subprofessionicon/sub_hunter_icon.png",
    "Incantation Medic":
        "op_misc/subprofessionicon/sub_incantationmedic_icon.png",
    Instructor: "op_misc/subprofessionicon/sub_instructor_icon.png",
    Juggernaut: "op_misc/subprofessionicon/sub_unyield_icon.png",
    Liberator: "op_misc/subprofessionicon/sub_librator_icon.png",
    Loopshooter: "op_misc/subprofessionicon/sub_loopshooter_icon.png",
    Lord: "op_misc/subprofessionicon/sub_lord_icon.png",
    Marksman: "op_misc/subprofessionicon/sub_fastshot_icon.png",
    "Mech-accord Caster": "op_misc/subprofessionicon/sub_funnel_icon.png",
    Merchant: "op_misc/subprofessionicon/sub_merchant_icon.png",
    "Multi-target Medic": "op_misc/subprofessionicon/sub_ringhealer_icon.png",
    "Mystic Caster": "op_misc/subprofessionicon/sub_mystic_icon.png",
    "Phalanx Caster": "op_misc/subprofessionicon/sub_phalanx_icon.png",
    Pioneer: "op_misc/subprofessionicon/sub_pioneer_icon.png",
    "Primal Caster": "op_misc/subprofessionicon/sub_primcaster_icon.png",
    "Primal Protector": "op_misc/subprofessionicon/sub_primprotector_icon.png",
    Protector: "op_misc/subprofessionicon/sub_protector_icon.png",
    "Push Stroker": "op_misc/subprofessionicon/sub_pusher_icon.png",
    Reaper: "op_misc/subprofessionicon/sub_reaper_icon.png",
    Ritualist: "op_misc/subprofessionicon/sub_ritualist_icon.png",
    "Sentry Protector": "op_misc/subprofessionicon/sub_shotprotector_icon.png",
    "Shaper Caster": "op_misc/subprofessionicon/sub_soulcaster_icon.png",
    "Single-target Medic": "op_misc/subprofessionicon/sub_physician_icon.png",
    Skyranger: "op_misc/subprofessionicon/sub_skywalker_icon.png",
    Soloblade: "op_misc/subprofessionicon/sub_musha_icon.png",
    "Splash Caster": "op_misc/subprofessionicon/sub_splashcaster_icon.png",
    Spreadshooter: "op_misc/subprofessionicon/sub_reaperrange_icon.png",
    "Standard Bearer": "op_misc/subprofessionicon/sub_bearer_icon.png",
    Summoner: "op_misc/subprofessionicon/sub_summoner_icon.png",
    Swordmaster: "op_misc/subprofessionicon/sub_sword_icon.png",
    Tactician: "op_misc/subprofessionicon/sub_tactician_icon.png",
    Therapist: "op_misc/subprofessionicon/sub_healer_icon.png",
    Trapmaster: "op_misc/subprofessionicon/sub_traper_icon.png",
    "Wandering Medic": "op_misc/subprofessionicon/sub_wandermedic_icon.png",
};

const nationIdMap: { [key: string]: string } = {
    "Abyssal Hunters": "op_misc/camplogo/logo_abyssal.png",
    Ægir: "op_misc/camplogo/logo_egir.png",
    Babel: "op_misc/camplogo/logo_babel.png",
    Blacksteel: "op_misc/camplogo/logo_blacksteel.png",
    Bolívar: "op_misc/camplogo/logo_bolivar.png",
    "Chiave's Gang": "op_misc/camplogo/logo_chiave.png",
    Columbia: "op_misc/camplogo/logo_columbia.png",
    Dublinn: "op_misc/camplogo/logo_dublinn.png",
    "Elite Op": "op_misc/camplogo/logo_elite.png",
    Followers: "op_misc/camplogo/logo_followers.png",
    Glasgow: "op_misc/camplogo/logo_glasgow.png",
    Higashi: "op_misc/camplogo/logo_higashi.png",
    Iberia: "op_misc/camplogo/logo_iberia.png",
    "Karlan Trade": "op_misc/camplogo/logo_karlan.png",
    Kazimierz: "op_misc/camplogo/logo_kazimierz.png",
    "L.D.A.": "op_misc/camplogo/logo_lee.png",
    "L.G.D.": "op_misc/camplogo/logo_lgd.png",
    "Laios' Party": "op_misc/camplogo/linkage/logo_laios.png",
    Laterano: "op_misc/camplogo/logo_Laterano.png",
    Leithanien: "op_misc/camplogo/logo_Leithanien.png",
    Lungmen: "op_misc/camplogo/logo_lungmen.png",
    Minos: "op_misc/camplogo/logo_minos.png",
    "Op A4": "op_misc/camplogo/logo_action4.png",
    "Op Reserve A1": "op_misc/camplogo/logo_reserve1.png",
    "Op Reserve A4": "op_misc/camplogo/logo_reserve4.png",
    "Op Reserve A6": "op_misc/camplogo/logo_reserve6.png",
    "Penguin Logistics": "op_misc/camplogo/logo_penguin.png",
    "Pinus Sylvestris": "op_misc/camplogo/logo_pinus.png",
    "Rhine Lab": "op_misc/camplogo/logo_rhine.png",
    "Rhodes Island": "op_misc/camplogo/logo_rhodes.png",
    "Rim Billiton": "op_misc/camplogo/logo_rim.png",
    "S.W.E.E.P.": "op_misc/camplogo/logo_sweep.png",
    Sami: "op_misc/camplogo/logo_sami.png",
    Sargon: "op_misc/camplogo/logo_sargon.png",
    Siesta: "op_misc/camplogo/logo_siesta.png",
    Siracusa: "op_misc/camplogo/logo_siracusa.png",
    Sui: "op_misc/camplogo/logo_sui.png",
    "Team Rainbow": "op_misc/camplogo/linkage/logo_rainbow.png",
    "U.S.S.G.": "op_misc/camplogo/logo_student.png",
    Ursus: "op_misc/camplogo/logo_ursus.png",
    Victoria: "op_misc/camplogo/logo_victoria.png",
    Yan: "op_misc/camplogo/logo_yan.png",
};

export { professionMap, subProfessionIdMap, nationIdMap };
